POST http://localhost:5000/user/signup
Content-Type: application/json

{
    "username": "yash",
    "password": "123456",
    "public_key": "",
    "type": "Customer"
}
###

POST http://localhost:5000/user/login
Content-Type: application/json

{
    "username": "yash",
    "password": "123456",
    "public_key": "777"
}
###

GET http://localhost:5000/user/logout/
